In [41]:
import numpy as np

In [42]:
A=np.array([
    [1,2,3],
    [4,5,6]
])
print(A) # dimension de 2X3

[[1 2 3]
 [4 5 6]]


In [43]:
A.shape # pour regarder la dimension (lignes, colonnes)

(2, 3)

**Accéder aux éléments**

In [44]:
A[0,1] #0 lignes /  1 colonnes 

np.int64(2)

In [45]:
#ligne compléte 
A[0]

array([1, 2, 3])

In [46]:
A[:,1]  #colonnes complète 

array([2, 5])

**opérations**

In [47]:
B=np.array([
    [7,8,9],
    [1,2,3]
])
print(A+B)

[[ 8 10 12]
 [ 5  7  9]]


In [48]:
#multiplication par scalaire 
A*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [53]:
C=B.T
C

array([[7, 1],
       [8, 2],
       [9, 3]])

In [54]:
#produit matriciel 
np.dot(C,B)

array([[50, 58, 66],
       [58, 68, 78],
       [66, 78, 90]])